### ISSUE TITLE
変換がうまくいかない例

### ISSUE THREAD

**Issue by nishi3da** [nagataaaas/Kanjize#2]
漢数字と算用数字の変換を探していたら、delta114514さんのKanjizeを発見しました。

早速、組み込ませて頂いたのですが、テストの段階で、漢数字→算用数字の変換のバグを発見しました。

 import kanjize
 print(kanjize.kanji2int("一億二千三百四十五万六千七百八十九"))
 print(kanjize.kanji2int("一兆二千三百四十五万六千七百八十九"))
 print(kanjize.kanji2int("十五億二千三百四十五万六千七百八十九"))

実行結果は
1000023456789（期待結果は、123456789）
10000000023456789（期待結果は、1000023456789）
1523456789（期待結果通り）
となりました。

お手すきの際にでも修正があると嬉しいです

**Comment by nagataaaas** [comment]
値の変換ライブラリなのにこんなバグがあるとはお恥ずかしい…

最新版でそもそもの値変換の流れを変え、このようなバグが発生しないようにしました。

ご指摘いただきありがとうございます。

**Comment by nishi3da** [comment]
自分で作ろうかと着手し始めたところで、助かりました。

おかげで、旧字体への変換部分の作成のみに注力できそうです。

素早い修正、本当にありがとうございました。

感謝です。


2020年10月28日(水) 20:34 delta114514 <notifications@github.com>:
