### ISSUE TITLE
ascii number with kanji

### ISSUE THREAD

**Issue by Naoki-Yatsu** [nagataaaas/Kanjize#3]
Hi, mixed ascii number with kanji are not working for some case. I think previously it was working (on 0.1.0?). I would appreciate if you library support it.

```
> import kanjize
> kanjize.__version__
'0.2.0'
> from kanjize import kanji2int
> kanji2int('4百万')
4
```

**Comment by nagataaaas** [comment]
Thanks for reporting this.
This is obviously unwanted behavior to users. But, I coded not to parse the kanjis like the example you showed.

kanjis which has number in itself will be parsed with setting `style='mixed'`.
`style='mixed'` is made to parse the string in the format of `([0-9]+千?[万億兆京垓]?)+` like `'5千万'`, `'453万4千'`.
any of '千百十' can't be used like `'3千4百2十万'`.
So, this is not a bug.

But, I think those strings should be parsed.
I updated this library and now it can parse strings like those.
See test case
https://github.com/nagataaaas/Kanjize/blob/88ef0cd53b9c1786bdc9570a40f68122dd95be08/test/test.py#L41-49

Thank you.

### Japanese:
報告ありがとうございます。
これはライブラリの利用者にとっては明らかに異常な挙動ですが、例のような文字列をパースするようには作成していません。

`.isnumeric()`が`True`になるようなキャラクタが入っている文字列を`style='mixed'`としてパースしますが、これは`'5千万'`, `'453万4千'`のように`([0-9]+千?[万億兆京垓]?)+`とマッチするような文字列のパースを目的としています。
'千百十'のうちのどれも、`'3千4百2十万'`のように用いることはできません。
ので、これはバグではありません。

しかし、例に挙げたような文字列をパースで来た方がいいのは確かです。
ライブラリをアップデートし、パースできるように書き換えました。
テストを追加しているので、ご覧いただければどのような文字列が新たにサポートされたのかがわかると思います。

ありがとうございます。

**Comment by Naoki-Yatsu** [comment]
Thank you for you quick support!
