### ISSUE TITLE
小数点を含む表記

### ISSUE THREAD

**Issue by schnell3526** [nagataaaas/Kanjize#4]
便利なライブラリを開発していただきありがとうございます。

使用している際に小数点を含む漢字表記に対して思うような結果がでなかったので報告させていただきます。

```python
from kanjie import knji2int

print(kanji2int('1.5億'))
# 500000001
```

「int」と漢数字の変換の趣旨にずれるのかもしれませんが、このような場合はエラーを出す等だけでも良いと思いますのでお手隙の際に対処していただければ幸いです。

**Comment by nagataaaas** [comment]
ご指摘ありがとうございます。

本来想定していた使い方ではないですが、確かに`250.2千`などの表記は一般に見るものであり、対応する必要があると判断しました。

ver. 1.1.0 (03a963764f5228bfaf8adf998cd7c059b5c20042) から新たにパース出来るように変更しました。

ありがとうございました。
