### ISSUE TITLE
赤字の変換「kanji2int("-1.2兆")」ができないようです。

### ISSUE THREAD

**Issue by happytechspot** [nagataaaas/Kanjize#5]
![image](https://user-images.githubusercontent.com/78670590/201469246-6ec138d5-bea4-4b9b-a8ea-8fda59e9d115.png)

**Comment by nagataaaas** [comment]
もともと負の数をパースするように作っていない為です。
とはいえ、パース出来ないように置いておく理由もないと判断したため、ver.1.2.0で対応させていただきました。

ありがとうございます。
