### ISSUE TITLE
0 is not in kanji dictionary 

### ISSUE THREAD

**Issue by jseo0703** [nagataaaas/Kanjize#7]
Hello, 

This library helps me a lot. Thank you.
But it seems tricky when trying to convert serial number like 012-345-6789, because there is no kanji representing 0 in the dictionary. 
Is there any reason for not including 0 in the dictionary?

Thank you very much for your reply for advance.

**Comment by nagataaaas** [comment]
I assume that you are trying to convert `012-345-6789` into kanji with code like below
```python
number = '012-345-6789'

result = ''
for c in number:
    if c != '-':
        result += number2kanji(c)
    else:
        result += '-'
```

As an answer for your question, I didn't intended to drop support for 0. I just forgot it(sorry)

I'm going to support `0` in next release.

**Comment by nagataaaas** [comment]
added support 0 in 1.4.0.

try upgrading kanjize.
